### ISSUE TITLE
times not imported with owncloud

### ISSUE THREAD

**Issue by 242bpm** [gggard/AndroidCaldavSyncAdapater#53]
Easy to setup. All events were imported from my owncloud account. But all events were imported as "allday" without time information. I also checked the android sqlite database - all dtstarts and  dtends are saved with timestamps of 00:00:00 o'clock.

event example from my own cloud account:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar
BEGIN:VEVENT
CREATED;VALUE=DATE-TIME:20130413T145505Z
UID:75bc1d5a14
LAST-MODIFIED;VALUE=DATE-TIME:20130413T145505Z
DTSTAMP;VALUE=DATE-TIME:20130413T145505Z
SUMMARY:Barbara
DTSTART;VALUE=DATE-TIME:20130414T090000Z
DTEND;VALUE=DATE-TIME:20130414T115500Z
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR

results in dtstart and dtend of 1365897600000 (So 14 Apr 2013 00:00:00) in android database.

Is there anything else i can provide?

**Comment by timoberger** [comment]
This is fixed with commit f7ddbb81c5d1c5ed5fc51de267a2fa8f29d71454 and should be available with the next release.

**Comment by 242bpm** [comment]
Great! Thanks!

**Comment by nodiscc** [comment]
Maybe this should be closed?

**Comment by maste9** [comment]
On 1.7 this problem is still valid which unfortunately prevents me from  banning google from my phone. Looking forward to next release so that I can finish my change to ownCloud. Thanks for your great work!

**Comment by timoberger** [comment]
this should be fixed with the next release.
i will close this issue (to get an overview of all unhandled issues).
feel free to reopen when needed.
